Donner la possibilité d'importer depuis un fichier excell le contenu d'un document de retour
gouchere/Lymytz_Erp pull request #44
Opened 2024-02-18 12:35 UTC by dowesw

- Ajout de la fonctionnalité d'importation sur les pages retour vente, retour achat, avoir vente, avoir achat
- Ajout d'une propriété hasMessageError sur les entités YvsComContenuDocAchat et YvsComContenuDocVente pour indiquer s'il y'a un message d'erreur pour une ligne

2024-07-21 05:40 UTC, gouchere requested changes

2024-10-20 12:09 UTC, dowesw commented on Lymytz_Web/web/pages/gescom/vente/yvs_bon_retour_vente.xhtml
> +                              allowTypes="/(\.|\/)(xls|xls?x)$/" fileUploadListener="#{managedBonAvoirVente.handleFileUploadXLS}"
Pas besoin vu que les csv ne sont pas utilisé par des profanes.

2024-10-20 12:09 UTC, dowesw commented on Lymytz_Web/web/pages/gescom/vente/yvs_bon_avoir_vente.xhtml
> +                              allowTypes="/(\.|\/)(xls|xls?x)$/" fileUploadListener="#{managedBonAvoirVente.handleFileUploadXLS}"
Toutes nos importations excell n'acceptent que des fichiers excell

2024-10-20 12:19 UTC, dowesw commented on Lymytz_Web/src/java/yvs/commercial/vente/ManagedBonAvoirVente.java
> +        // QTE - REFERENCE - DESIGNATION - UNITE - PRIX - REMISE - TAXE
La position n'a pas d'influence pour la récupération. On récupère en fonction du  nom de la colonne

2024-10-20 12:20 UTC, dowesw commented on Lymytz_Web/src/java/yvs/commercial/vente/ManagedBonAvoirVente.java
Corrigé.  
Mais peux tu m'envoyer le fichier que tu as utilisé?

2024-11-13 04:42 UTC, merged