Feature/80 chargement des acomptes liées plusieurs factures plus de 100 prend du temps
gouchere/Lymytz_Erp pull request #91
Opened 2024-07-14 14:39 UTC by dowesw

- [ ] Annulation de la vérification de comptabilisation des pieces lors du chargement
- [ ] Ajout d'un paginator et d'une recherche au niveau des pieces
- [ ] Définition des fonctions de calcul de reste d'acompte

2024-07-19 04:59 UTC, gouchere requested changes

2024-07-19 04:59 UTC, gouchere commented on Lymytz_Web/src/java/yvs/comptabilite/client/ManagedOperationClient.java
> +            double montant = y.getPieceVente().getMontant() + (reste != null ? reste : 0);
Les opérations ci ne sont pas equivalentes.
On ne récupère pas le reste, mais la somme de ce qui est déjà validé (l'encours validé)

2024-07-19 04:59 UTC, gouchere commented on Lymytz_Web/src/java/yvs/comptabilite/client/ManagedOperationClient.java
> +                compte.getVenteDiverses().add(buildBeanAcomptesVenteDivers(c));
Si possible renomer la variable venteDiverses en ventesEtDivers pour que ce soit plus explicite

2024-07-20 10:39 UTC, dowesw commented on Lymytz_Web/src/java/yvs/comptabilite/client/ManagedOperationClient.java
> +            double montant = y.getPieceVente().getMontant() + (reste != null ? reste : 0);
Fait

2024-07-20 10:39 UTC, dowesw commented on Lymytz_Web/src/java/yvs/comptabilite/client/ManagedOperationClient.java
> +                compte.getVenteDiverses().add(buildBeanAcomptesVenteDivers(c));
Fait

2024-07-21 05:35 UTC, gouchere approved these changes

2024-07-21 05:35 UTC, merged